### ISSUE TITLE
Sections closing tags

### ISSUE THREAD

**Issue by pverkind** [OpenITI/oimdp#6]
OpenITI mARkdown does generally not contain closing tags, but sometimes we do need to be able to indicate that a subsection is included in the text of a section, and that the text of the main section continues after the end of the subsection. 

We do this by repeating the tag of the subsection, but without a header (only a space after the pipes, like this: 

```
### | Section 1
# intro
### || Section 2
# short subsection
### || 
# Section 1 continues after end of section 2
```

Ideally, this should be converted to: 

```
      <div>
        <head>Section 1</head>
        <p>
          <lb/>intro
        </p>
        <div>
          <head>Section 2</head>
          <p>
            <lb/>short subsection
           </p>
        </div>
        <p>
          <lb/>Section 1 continues after end of section 2
        </p>        
      </div>
```

Currently it is converted to: 

```
      <div>
          <head>Section 1</head>
          <p>
              <lb/>intro
          </p>
          <div>
              <head>Section 2</head>
              <p>
                  <lb/>short subsection
              </p>
          </div>
          <div>
             <head></head>
              <p>
                  <lb/>Section 1 continues after end of section 2
              </p>
          </div>      
      </div>
```

**Comment by raffazizzi** [comment]
The "closing" section headers are correctly identified as `SectionHeader`s by the the parser. It should be up to converters to determine what to do with `SectionHeader`s that are not followed by any other `LinePart`.

I moved this issue to oitei to address it there: https://github.com/OpenITI/oitei/issues/7
